import { StyleSheet, Dimensions } from 'react-native';

const { width, height } = Dimensions.get('window');

export const documentosStyles = StyleSheet.create({
  container: {
    flex: 1,
  },
  contentContainer: {
    backgroundColor: 'rgba(255, 255, 255, 0.85)',
    borderRadius: 20,
    padding:16,
    paddingTop:20,
    marginTop:12,
    marginBottom: 12,
  },
  marker: {
    position: 'absolute', 
    zIndex:1,
    top:-70,
    right:8,
    marginBottom:-60,
    width: 60,
    height: 60,
    borderRadius: 10,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.23,
    shadowRadius: 2.62,
    elevation: 6,
  },
  title: {
    fontSize: 28,
    textTransform: 'capitalize',
    color: '#003366',
    marginBottom: 28,
    textAlign: 'center',
    fontFamily: 'Lora-Bold',
  },
  subtitle: {
    fontSize: 22,
    fontFamily: 'Lora-SemiBold',
    textTransform: 'capitalize',
    textAlign: 'center',
    color: '#003366',
    marginBottom:20,
  },
  subtitleDos:{
    fontSize: 18,
    fontFamily: 'Lora-SemiBold',
    textTransform: 'capitalize',
    textAlign: 'center',
    color: '#003366',
    marginBottom: 8,
  },
  paragraph: {
    fontSize: 16,
    lineHeight: 22,
    color: '#333',
    marginBottom: 8,
    textAlign: 'justify',
    fontFamily: 'Lora-Regular',
  },
  list: {
    marginLeft: 8,
    marginBottom: 8,
  },
  listItem: {
    fontSize: 16,
    lineHeight: 24,
    color: '#333',
    marginBottom: 5,    
    textAlign: 'justify',
    fontFamily: 'Lora-Regular',
  },
  keyword: {
    fontFamily: 'Lora-SemiBoldItalic',
    textTransform: 'capitalize',
    // color:'#1C4F7C',
    color: '#003366',
    fontSize: 16,
  },
  lessonImage: {
    width: '100%',
    height: 200,
    resizeMode: 'cover',
    borderRadius: 10,
  },
  videoContainer: {
    left:8,
    marginTop: 12,
    position: 'relative',
    width: width - 16,
    height: 205,
    marginBottom: 20,
    borderRadius: 10,
    overflow: 'hidden',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.23,
    shadowRadius: 2.62,
    elevation: 4,
  },
  fullscreenVideoContainer: {
    position: 'absolute',
    top: 0,
    left: 0,
    width: 380,
    height: 700,
    zIndex: 10,
  },
  videoWrapper: {
    width: '100%',
    height: '100%',
  },
  video: {
    width: '100%',
    height: '100%',
  },
  fullscreenVideo: {
    position: 'absolute',
    top: 160,
    left: -230,
    bottom: 0,
    right: 0,
    width: height,
    height: width,
  },
  controls: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    padding: 10,
  },
  fullscreenControls: {
    position: 'absolute',
    top:317,
    left:-306,
    width: height - 148,
    height: 70,
    transform: [{ rotate: '90deg' }],
    borderRadius:10,
  },
  progressBar: {
    width: '100%',
    height: 2,
    marginBottom: 10,
  },
  fullscreenProgressBar: {
    position: 'absolute',
    left: -height / 2 + 40,
    bottom: 20,
    width: height - 80,
    transform: [{ rotate: '90deg' }],
  },
  buttonContainer: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
    marginBottom: 8,
  },
  button: {
    backgroundColor: '#16A6FA',
    padding: 10,
    borderRadius: 10,
    alignItems: 'center',
    flex: 1,
    marginHorizontal: 8,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.23,
    shadowRadius: 2.62,
    elevation: 2,
  },
  buttonText: {
    color: 'white',
    fontSize: 22,
    fontFamily: 'Lora-Bold',
  },
  toolImage:{
    width:'height',
    height:width +200,
  },
  mayuscula:{
    textTransform: 'uppercase',
    fontFamily: 'Lora-SemiBoldItalic',
    // color:'#1C4F7C',
    color: '#003366',
    fontSize: 16,
  },
});

