// styles.js
import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    fontFamily: 'PlayfairDisplay-SemiBold',
    textTransform: 'capitalize',
  },
  backButton: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 10,
    backgroundColor: '#16A6FA',
    borderRadius: 5,
    marginBottom: 10,
  },
  backButtonText: {
    color: '#fff',
    marginLeft:4 ,
    fontSize: 16,
  },
  content: {
    alignItems: 'center',
  },
  // welcomeText: {
  //   fontSize: 24,
  //   fontWeight: 'bold',
  //   color: '#fff',
  //   textAlign: 'center',
  //   marginTop: 20,
  //   fontFamily: 'PlayfairDisplay_700Bold',
  // },
  buttonContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-around',
    width: '100%',
    padding: 10,
  },
  button: {
    backgroundColor: 'white',
    padding: 20,
    borderRadius: 15,
    width: '45%',
    alignItems: 'center',
    marginVertical: 10,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.23,
    shadowRadius: 2.62,
    elevation: 2,
  },
  buttonText: {
    color: '#333',
    fontSize: 16,
    // fontWeight: 'bold',
    textAlign: 'center',
    fontFamily: 'Lora-SemiBold',
    textTransform: 'capitalize',
  },
  toolsContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-around',
    padding: 10,
  },
  toolButton: {
    backgroundColor: 'white',
    padding: 20,
    borderRadius: 15,
    width: '45%',
    alignItems: 'center',
    marginVertical: 10,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.23,
    shadowRadius: 2.62,
    elevation: 2,
  },
  markerImage: {
    width: 10,
    height: 10,
    position: 'absolute',
    top: 5,
    right: 5,
  },
  markervideo: {
    width: '100%',
    height: 200,
    marginVertical: 10,
    marginHorizontal: 5,
  },
  powerPointButton: {
    backgroundColor: '#0078D4',
    padding: 10,
    borderRadius: 5,
    marginTop: 10,
  },
  powerPointButtonText: {
    color: 'white',
    // fontWeight: 'bold',
  },
  image: {
    width: 50,
    height: 50,
    resizeMode: 'contain',
  },
  headerBackground: {
    backgroundColor: '#16A6FA',
    height: 50,
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
  },
  waveContainer: {
    position: 'absolute',
    top: 50,
    left: 0,
    right: 0,
    height: 50,
    overflow: 'hidden',
  },
  wave: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: 0,
    height: '100%',
    backgroundColor: '#16A6FA',
  },
  
});